### ISSUE TITLE
Create the Technical file for MHRA 

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/TheOpenVoiceFactory#73]
We need to submit a technical file to the MHRA so that they can accept The Open Voice Factory as a medical device. 

Here's what we need in a technical file for the MHRA (as provided by @greg-westnine):

- [ ]  Detailed description of the system (from the architecture wiki) #82 
- [ ] Statement of Essential Principals, indicating how the requirements of the regulation are being met (eg conformance with standards) #85
- [ ]  Risk Register and Summary #83
- [ ]  Collected issues defining the requirements of the system #86
- [ ]  Release notes #87
- [ ]  Test cases and Test reports #88
- [ ]  Quality Management System (QMS)
- [ ]  Improvements Register
- [ ]  Evidence of post market surveillance
- [ ]  Declaration of conformance #89

**Comment by greg-westnine** [comment]
Things to include in the Technical File
- [ ] Detailed description of the system (from the architecture wiki)
- [ ] Risk Register and Summary
- [ ] Collected issues defining the requirements of the system
- [ ] Release notes
- [ ] Test cases and Test reports
- [ ] QMS
- [ ] Improvements Register
- [ ] Evidence post market surveillance
- [ ] Declaration of conformance

**Comment by greg-westnine** [comment]
QMS = Quality Management System - have updated.  Basically it is our policies.

**Comment by greg-westnine** [comment]
This document might be useful 
[Summary of Technical Documentation Conformity.docx](https://github.com/eQualityTime/TheOpenVoiceFactory/files/2241877/Summary.of.Technical.Documentation.Conformity.docx)

**Comment by joereddington-public** [comment]
Thank you for adding issues for each of these - that's going to make life easier. :)

**Comment by greg-westnine** [comment]
I have been thinking about the roadmap.  I decided a visual representation might be helpful so have created this https://docs.google.com/spreadsheets/d/1LhxRgpai2V81J0bDuiULLEfngxrJ050ljg3rrjk0DHg/edit?usp=sharing

I think trying activity to organisational goals is a good thing to do.  I can imagine linking this to the risk register and have therefore added a stream for this, although it is currently empty.  Maybe there are more things to define as goals.
Also I think 'sprints for comic relief' isn't very enlightening.  What do we think Comic Relief want to see?  Even if we don't know the detail of what changes maybe we know the main themes.

The timescales might be highly speculative, but I feel like putting some kind of marker down is a good thing.

**Comment by joereddington-public** [comment]
'sprints for comic relief' should probably say "We're putting together a group of stakeholders, who will tell us what they want, and we'll do some agile sprints with out coders to deliver it."  does that make sense?

**Comment by joereddington-public** [comment]
Looking at #86 - the title doesn't appear to aggree with the text in *this* issues header - @greg-westnine - please do some expansion.
